name: apps_packagebox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^15.1.1
  shared_preferences: ^2.5.2
  http: ^1.1.1
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/